project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - posts/
  resources:
    - data/Formal_Writeup_Blogpost_of_what_is_the_meaning_of_the_estimation_error.pdf

website:
  title: "Blog of Daniel Strauss"
  site-url: "https://daniel-strauss.github.io/blog/"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax
